/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.1.2
 * Product:       scd4x
 * Model-Version: 2.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include "scd4x_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c_hal.h"
#include <inttypes.h>  // PRIx64
#include <stdio.h>     // printf
#include <avr/io.h>
#define F_CPU 4000000
#include <util/delay.h>
#include <stdlib.h>

#include "serlcd.h"

#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec



#define sensirion_hal_sleep_us sensirion_i2c_hal_sleep_usec

char dsp_buff1[21];
char dsp_buff2[21];
char dsp_buff3[21];
char dsp_buff4[21];

void convert_and_print_serial(uint16_t* serial_raw) {
    uint64_t serial_as_int = 0;
    sensirion_common_to_integer((uint8_t*)serial_raw, (uint8_t*)&serial_as_int,
                                LONG_INTEGER, 6);
   // printf("0x%" PRIx64, serial_as_int);
}

int main(void) {
    void init_spi0_SerLCD (void)
    {
	    PORTA.DIR |= PIN4_bm;  // MOSI channel
	    PORTA.DIR &= ~PIN5_bm; // MISO channel
	    PORTA.DIR |= PIN6_bm;  // SCK channel
	    PORTA.DIR |= PIN7_bm;  // SS channel
	    
	    SPI0_CTRLA = SPI_ENABLE_bm | SPI_MASTER_bm | SPI_PRESC_DIV4_gc; // enables SPI communication, initializes AVR as master, and sets AVR speed to 1MHz
    }
	
	
	int16_t error = NO_ERROR;
    sensirion_i2c_hal_init();
    scd4x_init(SCD41_I2C_ADDR_62);

    //uint16_t serial_number[3] = {0};
    sensirion_hal_sleep_us(30000);
    // Ensure sensor is in clean state
    error = scd4x_wake_up();
    if (error != NO_ERROR) {
        printf("error executing wake_up(): %i\n", error);
    }

    error = scd4x_stop_periodic_measurement();
    if (error != NO_ERROR) {
        printf("error executing stop_periodic_measurement(): %i\n", error);
    }

    error = scd4x_reinit();
    if (error != NO_ERROR) {
        printf("error executing reinit(): %i\n", error);
    }

    // If temperature offset and/or sensor altitude compensation
    // is required, you should call the respective functions here.
    // Check out the header file for the function definitions.
    // Start periodic measurements (5sec interval)
    error = scd4x_start_periodic_measurement();
    if (error != NO_ERROR) {
        printf("error executing start_periodic_measurement(): %i\n", error);
        return error;
    }
    //
    // If low-power mode is required, switch to the low power
    // measurement function instead of the standard measurement
    // function above. Check out the header file for the definition.
    //
    bool data_ready = false;
    uint16_t co2_concentration = 0;
    int32_t temperature = 0;
    int32_t relative_humidity = 0;
    uint16_t repetition = 0;
    for (repetition = 0; repetition < 50; repetition++) {
        //
        // Slow down the sampling to 0.2Hz.
        //
        sensirion_hal_sleep_us(5000000);
        //
        // If ambient pressure compensation during measurement
        // is required, you should call the respective functions here.
        // Check out the header file for the function definition.
        error = scd4x_get_data_ready_status(&data_ready);
        if (error != NO_ERROR) {
            printf("error executing get_data_ready_status(): %i\n", error);
            continue;
        }
        while (!data_ready) {
            sensirion_hal_sleep_us(100000);
            error = scd4x_get_data_ready_status(&data_ready);
            if (error != NO_ERROR) {
                printf("error executing get_data_ready_status(): %i\n", error);
                continue;
            }
        }
        error = scd4x_read_measurement(&co2_concentration, &temperature,
                                       &relative_humidity);
        if (error != NO_ERROR) {
           // printf("error executing read_measurement(): %i\n", error);
            continue;
        }
		//uint8_t co2 = co2_concentration;
		float temp = temperature / 1000.0;
		float rh = relative_humidity / 1000.0;
		sprintf(dsp_buff1, "CO2    : %u ppm    ", co2_concentration); //display CO2 concent
		sprintf(dsp_buff2, "Temp  C: %.2f C    ", temp); //display temp
		sprintf(dsp_buff3, "RH: %.2f percent", rh); //display relative humidity
		
		SerLCD_init();
		update_SerLCD(co2_concentration, temp, rh);
    }

    return NO_ERROR;
}
